# Generated by Django 5.1.4 on 2025-01-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('diagnostics', models.CharField(max_length=200)),
                ('observations', models.CharField(max_length=300)),
                ('treatments', models.CharField(max_length=300)),
                ('misc', models.CharField(max_length=300)),
            ],
        ),
    ]
